#Anything that is optional which you are not using, just delete that line. You can also delete any of the '#comments'
 
modLoader="javafml" #mandatory
loaderVersion="[35,)" #mandatory
license="MIT License Copyright (c) [2021] [Pranav T]" #optional
 
[[mods]] 
modId="pranavtplatinummod" 
version="0.1" 
displayName="Platinum Mod" 	
displayURL="https://github.com/awsame303/PlatinumMod" 
logoFile="titaniummodicon.png" #optional
credits="titanium textures from bedlessnoob 200k pack" 
authors="awsame303(pranavt)" 
description='''
Hello o/
I am a new developer who just started making minecraft mods. I am adding a new ore to the game called
Titanium. It works like diamond except is more powerful and does more things. It might be really buggy
since this is my first mod, but I hope you enjoy it!!!
''' 
 